openapi: 3.0.0
info:
  title: Glance API
  description: API end-points documentation for Glance project
  version: 0.0.1
servers:
  - url: http://HOST_URL
    description: Default host URL for development purpose
components:
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /user/login:
    post:
      tags:
        - User
      summary: User login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                email: "test@email.com"
                password: "Password1"
      responses:
        '202':
          description: JWT token. User login result.
          content:
            application/json:
              schema:
                type: object
                example:
                  token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /user:
    post:
      tags:
        - User
      summary: New user
      security:
        - bearer: []
      description: New user creation by admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                email: test@email.com
                room: 312
                first_name: Jhon
                last_name: Doe
                continent: Europe
                country: UK
                city: London
                site: 4B
                block: 12F
                floor: 3
      responses:
        '201':
          description: User created
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
    get:
      tags:
        - User
      summary: Get user profile
      description: Get user profile for further integration and logic
      security:
        - bearer: []
      responses:
        '200':
          description: Public user profile
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 321
                  first_name: John
                  last_name: Doe
                  image: https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg
                  given_name: Username
                  room: 312
                  email: test@email.com
                  phone: +1 (042) 412 54 12
                  is_first_time: true
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
    patch:
      tags:
        - User
      summary: Update user profile
      description: Updating user profile with new password after first login, update in the settings page, etc
      security:
        - bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                image: https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg
                given_name: UsernameNew
                email: newtest@email.com
                phone: +1 (042) 412 54 00
      responses:
        '202':
          description: User updated
          content:
            application/json:
              schema:
                type: object
                example:
                  id: 321
                  first_name: John
                  last_name: Doe
                  image: https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg
                  given_name: Username
                  room: 312
                  email: test@email.com
                  phone: +1 (042) 412 54 12
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /user/update_password:
    patch:
      tags:
        - User
      security:
        - bearer: []
      summary: Update user password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                password: Password1
      responses:
        '202':
          description: User updated
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /event:
    post:
      tags:
        - Events
      summary: Create event
      description: Create event from admin panel
      security:
        - bearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                title: John Doe's meeting
                date: 2019-10-04T16:56:07+03:00
                location: Campus 12B
                category: 1
                open_to: London
                max_attendees: 20
                description: Just meeting with famous person!
      responses:
        '201':
          description: Event created.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
    get:
      tags:
        - Events
      summary: Get single event
      security:
        - bearer: []
      parameters:
        - in: query
          name: eid
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: "
              Categories: \n
                Scene - 0; \n
                Balance - 1; \n
                Horizons - 2; \n
                SavedEvents - 3.
              Types: \n
                FreeType - 0; \n
                PaidType - 1. \n
              "
          content:
            application/json:
              example:
                id: 21
                title: John Doe's meeting
                date: 2019-10-04T16:56:07+03:00
                location: Campus 12B
                category: 1
                payment_type: 0
                open_to: London
                max_attendees: 20
                description: Just meeting with famous person!
                is_waitlist_open: true
                is_saved: false
                status: 1
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /event/all:
    get:
      tags:
        - Events
      summary: Get events list
      description: Get list of events
      security:
        - bearer: []
      responses:
        '200':
          description: "
          Categories: \n
            Scene - 0; \n
            Balance - 1; \n
            Horizons - 2; \n
            SavedEvents - 3.
          Types: \n
            FreeType - 0; \n
            PaidType - 1. \n
          "
          content:
            application/json:
              example:
                events: [
                {
                  "id": 21,
                  "title": "John Doe's meeting",
                  "date": "2019-10-04T16:56:07+03:00",
                  "location": "Campus 12B",
                  "category": 1,
                  "payment_type": 0,
                  "open_to": "London",
                  "max_attendees": 20,
                  "description": "Just meeting with famous person!",
                  "is_saved": false,
                  "user_status": 1
                }
                ]
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /event/filtered:
    patch:
      tags:
        - Events
      summary: Get filtered events
      security:
        - bearer: []
      description: DayTripsAndSocials - 0;
        MindAndBody - 1;
        SkillsAndCareer - 2;
        SavedEvents - 3;
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                filters: [1, 2, 3]
      responses:
        '200':
          description: Response of the events getter
          content:
            application/json:
              example:
                events: [
                {
                  "id": 12,
                  "title": "John Doe's meeting",
                  "date": "2019-10-04T16:56:07+03:00",
                  "location": "Campus 12B",
                  "category": 1,
                  "payment_type": 0,
                  "open_to": "London",
                  "max_attendees": 20,
                  "description": "Just meeting with famous person!",
                  "user_status": 1
                }
                ]
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /event/save:
    patch:
      tags:
        - Events
      security:
        - bearer: []
      summary: Save event by user
      parameters:
        - in: query
          name: event_id
          schema:
            type: integer
          required: true
      responses:
        '201':
          description: Event saved.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /event/unsave:
    patch:
      tags:
        - Events
      security:
        - bearer: []
      summary: Unsave event by user
      parameters:
        - in: query
          name: event_id
          schema:
            type: integer
          required: true
      responses:
        '201':
          description: Event unsaved.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /event/status:
    patch:
      tags:
        - Events
      summary: Change event status by user
      security:
        - bearer: []
      description: "
      Statuses:
        Canceled - 0;
      	Joined - 1;
      	Pending - 2;
      	Waitlist - 3."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                status: 2
                event_id: 1
      responses:
        '201':
          description: Status has been changed.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /notification:
    post:
      summary: Create notification
      security:
        - bearer: []
      tags:
        - Notifications
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                notification_type: Building
                title: An update on the lifts
                body: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
                continent: Europe
                country: England
                city: London
                location: Glastonburry
      responses:
        '201':
          description: Notification has been created.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /notification/list:
    get:
      summary: Get notifications list
      security:
        - bearer: []
      tags:
        - Notifications
      responses:
        '200':
          description: Notifications list
          content:
            application/json:
              example:
                list: [
                {
                  "id": 123,
                  "created_at": "2019-10-04T16:56:07+03:00",
                  "title": "You collected a parcel",
                  "notification_type": "Parcel",
                  "sender": "Steve"
                },
                {
                  "id": 124,
                  "created_at": "2019-10-04T16:56:07+03:00",
                  "title": "Maintenance complete",
                  "notification_type": "Maintenance",
                  "sender": "Ellie"
                }
                ]
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /wellbeing:
    post:
      summary: Create new wellbeing request
      security:
        - bearer: []
      tags:
        - Wellbeing
      responses:
        '201':
          description: Wellbeing request has been created.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
    patch:
      summary: Update wellbeing request to status 'done'
      security:
        - bearer: []
      tags:
        - Wellbeing
      parameters:
        - in: query
          required: true
          name: request_id
          schema:
            example: 123
      responses:
        '202':
          description: Wellbeing request has been created.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /parcel/later:
    patch:
      summary: Change parcel status to 'take later'
      security:
        - bearer: []
      tags:
        - Parcels
      requestBody:
        required: true
        description: Parcel id and take time
        content:
          application/json:
            schema:
              example:
                parcel_id: 13
                date: "2019-10-04T16:56:07+03:00"
      responses:
        '202':
          description: Take later response.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /parcel:
    patch:
      summary: Change status of the parcel
      security:
        - bearer: []
      tags:
        - Parcels
      requestBody:
        required: true
        description:
          "TakeNow - 1;
          LeaveInRoom - 3."
        content:
          application/json:
            schema:
              example:
                parcel_id: 12
                new_status: 1
      responses:
        '202':
          description: Status changed.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /maintenance:
    post:
      summary: Create new maintenance request
      security:
        - bearer: []
      tags:
        - Maintenance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                images: ["base64-1", "base64-2"]
                description: I lost my umbrella in the cupboard. There is Narnia inside.
                user_id: 69
      responses:
        '201':
          description: Created.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /user/device:
    post:
      summary: Insert user device id
      security:
        - bearer: []
      tags:
        - User
      parameters:
        - in: query
          required: true
          name: device_id
          schema:
            example: ef3d3148-333c-4575-a2bc-0af99981291e
      responses:
        '202':
          description: Updated.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /maintenance/list:
    get:
      summary: Get user maintenance request
      security:
        - bearer: []
      tags:
        - Maintenance
      responses:
        '200':
          description: Maintenance requests list
          content:
            application/json:
              example:
                [
                {
                  "id": 123,
                  "created_at": "2019-10-04T16:56:07+03:00",
                  "images": ["https://avatars.slack-edge.com/2019-09-12/757692490512_45426d9e4f4f550e9a3f_72.jpg",
                             "https://avatars.slack-edge.com/2019-09-12/757692490512_45426d9e4f4f550e9a3f_72.jpg"],
                  "description": "My door is broken",
                  "user_id": 12
                },
                {
                  "id": 124,
                  "created_at": "2019-10-04T16:56:07+03:00",
                  "images": ["https://avatars.slack-edge.com/2019-09-12/757692490512_45426d9e4f4f550e9a3f_72.jpg",
                             "https://avatars.slack-edge.com/2019-09-12/757692490512_45426d9e4f4f550e9a3f_72.jpg"],
                  "description": "My couch is too hard",
                  "user_id": 12
                }
                ]
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /user/send_code:
    post:
      summary: Send code for renew forgotten password
      security:
        - bearer: []
      tags:
        - User
      parameters:
        - in: query
          required: true
          name: email
          schema:
            example: test@email.com
      responses:
        '200':
          description: Code has been sent.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
  /user/check_code:
    post:
      summary: Check code for existing
      security:
        - bearer: []
      tags:
        - User
      parameters:
        - in: query
          required: true
          name: email
          schema:
            example: test@email.com
        - in: query
          required: true
          name: code
          schema:
            example: KADBAHS
      responses:
        '200':
          description: Code is valid.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong code
        '500':
          description: Status Internal Error.
  /user/renew_pwd:
    post:
      summary: Enter new password
      security:
        - bearer: []
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                email: test@email.com
                password: 12345678
      responses:
        '202':
          description: Password has been updated.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong code
        '500':
          description: Status Internal Error.
  /user/admin:
    post:
      summary: Create new admin
      security:
        - bearer: []
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                first_name: Jon
                last_name: Doe
                email: admin@email.com
                image: https://www.kranjska-gora.si/media/SlikeIT/Galerije/kranjska-gora-1.jpg
                site_permissions: ["read", "create", "edit", "delete"]
                admin_permissions: ["read", "create", "edit", "delete"]
                resident_permissions: ["read", "upload"]
                chat_permissions: ["read", "send"]
                delivery_permissions: ["read", "create", "edit", "delete"]
                maintenance_permissions: ["read", "create", "edit", "delete"]
                wellbeing_permissions: ["read", "create", "edit", "delete"]
                events_permissions: ["read", "create", "edit", "delete"]
                notification_permissions: ["read", "create", "edit", "delete"]
      responses:
        '201':
          description: User created
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
    patch:
      summary: Update existing admin
      security:
        - bearer: []
      tags:
        - User
      requestBody:
        required: true
        content:
          application/json:
            schema:
              example:
                admin_id: 8
                first_name: Jon
                last_name: Doe
                email: admin@email.com
                image: https://www.kranjska-gora.si/media/SlikeIT/Galerije/kranjska-gora-1.jpg
                site_permissions: ["read", "create", "edit", "delete"]
                admin_permissions: ["read", "create", "edit", "delete"]
                resident_permissions: ["read", "upload"]
                chat_permissions: ["read", "send"]
                delivery_permissions: ["read", "create", "edit", "delete"]
                maintenance_permissions: ["read", "create", "edit", "delete"]
                wellbeing_permissions: ["read", "create", "edit", "delete"]
                events_permissions: ["read", "create", "edit", "delete"]
                notification_permissions: ["read", "create", "edit", "delete"]
      responses:
        '202':
          description: Admin has been updated.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
    delete:
      summary: Delete admin
      security:
        - bearer: []
      tags:
        - User
      parameters:
        - in: query
          name: aid
          schema:
            type: integer
          required: true
      responses:
        '202':
          description: Admin has been deleted.
        '400':
          description: Bad Request.
          content:
            application/json:
              schema:
                type: object
                example:
                  code: 400
                  error: wrong parameter
        '500':
          description: Status Internal Error.
